# Generated by Django 5.2.13 on 2026-06-16 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Resume', max_length=100)),
                ('file', models.FileField(upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Upload a valid PDF file.')])),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.FileField(blank=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Upload a valid logo file (SVG, PNG, JPG, JPEG, or WebP).')]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Upload a valid logo file (SVG, PNG, JPG, JPEG, or WebP).')]),
        ),
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
